# Generated by Django 4.1 on 2022-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_news_photo_alter_category_title_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d", verbose_name="Фото"
            ),
        ),
    ]
