# Generated by Django 4.1 on 2022-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0003_alter_news_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aboutus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(max_length=250, verbose_name="Телеграм аккаунт"),
                ),
                (
                    "whatsapp_link",
                    models.CharField(max_length=250, verbose_name="WhatsApp аккаунт"),
                ),
                ("email_link", models.CharField(max_length=250, verbose_name="Почта")),
            ],
            options={
                "verbose_name": "Информация о нас",
                "verbose_name_plural": "Информации о нас",
            },
        ),
    ]
